name       : solus-artwork
version    : '20'
release    : 35
source     :
    - https://github.com/solus-project/artwork/releases/download/v20/artwork-20.tar.xz : 5aa18389810ccf9332c6c90d805de272f7a31da9e2d5a76adc77eb405b91158d
license    :
    - GPL-2.0
    - CC-BY-3.0
    - CC-BY-SA-4.0
summary    : Official Solus artwork
component  :
    - desktop.theme
    - mate : desktop.theme
replaces   :
    - evolve-os-artwork
rundeps    :
    - mate : solus-artwork
patterns   :
    - mate : /usr/share/mate-background-properties
description: |
    Official Solus artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Legacy upgrade path
    ln -s solus $installdir/usr/share/backgrounds/evolve-os
