name       : solus-artwork
version    : '17'
release    : 32
source     :
    - https://github.com/solus-project/artwork/releases/download/v17/solus-artwork-17.tar.xz : c27d7fd687c16153df8d6013fe09a1464c1e52ac690d3cc228cf87a30c96183d
license    :
    - GPL-2.0
    - CCPL-Attribution-3.0
summary    : Official Solus artwork
component  :
    - desktop.theme
    - mate : desktop.theme
replaces   :
    - evolve-os-artwork
rundeps    :
    - mate : solus-artwork
patterns   :
    - mate : /usr/share/mate-background-properties
description: |
    Official Solus artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Legacy upgrade path
    ln -s solus $installdir/usr/share/backgrounds/evolve-os
