name       : solus-artwork
version    : '30.0'
release    : 50
source     :
    - https://github.com/getsolus/artwork/releases/download/30.0/artwork-30.tar.xz : 48a785feab7f5e0613a78b63871120137a7022f967858752ed8f6cfbea48f70f
license    :
    - CC-BY-3.0
    - CC-BY-SA-4.0
    - Distributable
    - GPL-2.0-only
    - Unsplash
summary    : Official Solus artwork
description: |
    Official Solus artwork
component  :
    - desktop.theme
    - mate : desktop.theme
    - plasma : desktop.kde
replaces   :
    - evolve-os-artwork
rundeps    :
    - mate : solus-artwork
    - plasma : solus-artwork
patterns   :
    - mate : /usr/share/mate-background-properties
    - plasma :
        - /usr/share/wallpapers
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Add Plasma-specific bits
    install -dm00644 $installdir/usr/share/wallpapers
    ln -s /usr/share/backgrounds/solus $installdir/usr/share/wallpapers/solus
    # Legacy upgrade path
    ln -s solus $installdir/usr/share/backgrounds/evolve-os
