name       : solus-artwork
version    : '24.0'
release    : 43
source     :
    - https://github.com/getsolus/artwork/releases/download/24.0/artwork-24.tar.xz : a403ad568d7318c0515ab51389294fbce9df0f29008842f45f97f27eef823c6e
license    :
    - CC-BY-3.0
    - CC-BY-SA-4.0
    - Distributable
    - GPL-2.0-only
    - Unsplash
summary    : Official Solus artwork
description: |
    Official Solus artwork
component  :
    - desktop.theme
    - mate : desktop.theme
    - plasma : desktop.kde
replaces   :
    - evolve-os-artwork
rundeps    :
    - mate : solus-artwork
    - plasma : solus-artwork
patterns   :
    - mate : /usr/share/mate-background-properties
    - plasma :
        - /usr/share/wallpapers
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Add Plasma-specific bits
    install -dm00644 $installdir/usr/share/wallpapers
    ln -s /usr/share/backgrounds/solus $installdir/usr/share/wallpapers/solus
    # Legacy upgrade path
    ln -s solus $installdir/usr/share/backgrounds/evolve-os
