name       : solus-artwork
version    : '22.0'
release    : 37
source     :
    - https://github.com/getsolus/artwork/releases/download/22.0/artwork-22.tar.xz : bae08993237e14fd58df91a2bd778ee1143a3636fa30f4bead13b9fc1d707cf8
license    :
    - CC-BY-3.0
    - CC-BY-SA-4.0
    - GPL-2.0-only
summary    : Official Solus artwork
description: |
    Official Solus artwork
component  :
    - desktop.theme
    - mate : desktop.theme
replaces   :
    - evolve-os-artwork
rundeps    :
    - mate : solus-artwork
patterns   :
    - mate : /usr/share/mate-background-properties
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Legacy upgrade path
    ln -s solus $installdir/usr/share/backgrounds/evolve-os
