name       : solus-artwork
version    : '28.0'
release    : 48
source     :
    - https://github.com/getsolus/artwork/releases/download/28.0/artwork-28.tar.xz : 13c47ccdea1174668a361cb8839089fd4e052558c6f9877f6396ee1a84bcf516
license    :
    - CC-BY-3.0
    - CC-BY-SA-4.0
    - Distributable
    - GPL-2.0-only
    - Unsplash
summary    : Official Solus artwork
description: |
    Official Solus artwork
component  :
    - desktop.theme
    - mate : desktop.theme
    - plasma : desktop.kde
replaces   :
    - evolve-os-artwork
rundeps    :
    - mate : solus-artwork
    - plasma : solus-artwork
patterns   :
    - mate : /usr/share/mate-background-properties
    - plasma :
        - /usr/share/wallpapers
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Add Plasma-specific bits
    install -dm00644 $installdir/usr/share/wallpapers
    ln -s /usr/share/backgrounds/solus $installdir/usr/share/wallpapers/solus
    # Legacy upgrade path
    ln -s solus $installdir/usr/share/backgrounds/evolve-os
