name       : solus-artwork
version    : '18'
release    : 33
source     :
    - https://github.com/solus-project/artwork/releases/download/v18/solus-artwork-18.tar.xz : b0bc15b2afe335184eee14cecbf8a18e8c55efd945117a6f4cf611b9057c3a94
license    :
    - GPL-2.0
    - CCPL-Attribution-3.0
summary    : Official Solus artwork
component  :
    - desktop.theme
    - mate : desktop.theme
replaces   :
    - evolve-os-artwork
rundeps    :
    - mate : solus-artwork
patterns   :
    - mate : /usr/share/mate-background-properties
description: |
    Official Solus artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Legacy upgrade path
    ln -s solus $installdir/usr/share/backgrounds/evolve-os
