name       : solus-artwork
version    : '21'
release    : 36
source     :
    - https://github.com/solus-project/artwork/releases/download/v21/artwork-21.tar.xz : b1aacbffa8edb12e68b8763168142cac08f7f5e6561f49c44a2547183135dfc2
license    :
    - GPL-2.0
    - CC-BY-3.0
    - CC-BY-SA-4.0
summary    : Official Solus artwork
component  :
    - desktop.theme
    - mate : desktop.theme
replaces   :
    - evolve-os-artwork
rundeps    :
    - mate : solus-artwork
patterns   :
    - mate : /usr/share/mate-background-properties
description: |
    Official Solus artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Legacy upgrade path
    ln -s solus $installdir/usr/share/backgrounds/evolve-os
