name       : solus-artwork
version    : '16'
release    : 31
source     :
    - https://github.com/solus-project/artwork/releases/download/v16/solus-artwork-16.tar.xz : 9c565e0a6834d50bf95af5d69a0194d178ba6db1ba9d5539ca8ef310a0e9be36
license    :
    - GPL-2.0
    - CCPL-Attribution-3.0
summary    : Official Solus Operating System artwork
component  :
    - desktop.theme
    - mate: desktop.theme
replaces   :
    - evolve-os-artwork
rundeps    :
    - mate: solus-artwork
patterns   :
    - mate: /usr/share/mate-background-properties
description: |
    Official Solus Operating System artwork
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Legacy upgrade path
    ln -s solus $installdir/usr/share/backgrounds/evolve-os
